### ISSUE TITLE
Dynamic peer creation should be a delegation, not an invocation.

### ISSUE THREAD

**Issue by cobward** [spruceid/kepler#108]
A peer can be permitted to host an orbit explicitly by the orbit manifest, or the controller can delegate the `#peer` capability to a Kepler instance. This second "dynamic" peer creation currently works through the invocation of the peer capability by the controller (or delegate), but it should be a delegation. This way the peer can connect to other peers in the orbit and prove that it has the authority to host the orbit by sharing the delegation.

**Comment by cobward** [comment]
@chunningham how would we feel about also changing the name of the capability from `#peer` to `#host`? `peer` sounds a bit wrong to me as it isn't a verb (well it is but we don't intend that meaning!)

**Comment by chunningham** [comment]
that would be fine I think, makes sense

**Comment by chunningham** [comment]
this was completed as part of the cacao-zcap task for both the sdk and the backend, marking as complete
