### ISSUE TITLE
Implement Kepler session keys

### ISSUE THREAD

**Issue by wyc** [spruceid/kepler#50]
As a User, I want to be able to issue a capability with my Web3 wallet to delegate privileges to a temporary session key. The capability should expire within a short configurable window, support secure erasure if used within a browser, and also allow for "break glass" revocation within an orbit manifest. This should allow for enhanced user interfaces that still support standards such as ZCAPs along with proper consent display to the user, instead of relying upon diverse signing implementations across different blockchains.

**Comment by chunningham** [comment]
Has been implemented in PR #54, except for revocation functionality.
