### ISSUE TITLE
Lock not acquirable for ipfs store.

### ISSUE THREAD

**Issue by cobward** [spruceid/kepler#67]
After an orbit is evicted from the cache, the orbit cannot be reloaded as a lock cannot be acquired on one of the sqlite stores:
```
IO error: could not acquire lock on "/tmp/kepler/.../....ks3db/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
```

**Comment by wyc** [comment]
We should really figure out the AWS S3 or DynamoDB backend for IPFS ~2-8 MB blocks. cc @sbihel 

What do we think would be a good store that's relatively cloud-agnostic?

**Comment by cobward** [comment]
This is still an issue post- rust-ipfs cutover. Perhaps there is an issue with how we are using `cached`?
